[project]
name = "GraphCreation"
version = "0.0.1"
authors = [
  { name="Christopher Oosthuizen", email="christopher.jan.oosthuizen@gmail.com" },
]
description = "Knowledge Graph Creation Library"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]